In [121]:
import numpy as np

###`Q-1:` Create a random 3x4 matrix with value between 0-100. And perform below tasks

    i. Sort this matrix. np.sort()
    ii. Sort this matrix based on values in 2nd column.
    iii. Sort this matrix based on max value in each row.
    iv. Sort based on elements value.


See examples:
```
arr =
    [[92 90 74]
    [ 6 63 93]
    [15 93 96]
    [70 60 48]]
```
```
i. np.sort
[[74 90 92]
 [ 6 63 93]
 [15 93 96]
 [48 60 70]]

ii. based on 2nd column
[[70 60 48]
 [ 6 63 93]
 [92 90 74]
 [15 93 96]]

iii. based on row max- ascending
[[15 93 96]
 [ 6 63 93]
 [92 90 74]
 [70 60 48]]

iv. based on elements value
[[ 6 15 48]
 [60 63 70]
 [74 90 92]
 [93 93 96]]

```

In [122]:
mat = np.random.randint(0, 100, 12).reshape(4, 3)
mat

array([[90, 57, 55],
       [33, 46, 51],
       [77, 37, 76],
       [20, 14, 60]])

In [123]:
# i. Sort this matrix. np.sort()
sorted_mat = np.sort(mat)
sorted_mat

array([[55, 57, 90],
       [33, 46, 51],
       [37, 76, 77],
       [14, 20, 60]])

In [124]:
#  ii. Sort this matrix based on values in 2nd column.
sorted_basedon_2nd_col = mat[mat[:, 1].argsort()]
sorted_basedon_2nd_col

array([[20, 14, 60],
       [77, 37, 76],
       [33, 46, 51],
       [90, 57, 55]])

In [125]:
# iii. Sort this matrix based on max value in each row.
# Step 1: get max value of each row
row_max = mat.max(axis=1)
print(row_max)
# Step 2: get sorted indices based on these max values
sorted_indices = row_max.argsort()
print(sorted_indices)
# Step 3: rearrange rows
sorted_arr = mat[sorted_indices]
sorted_arr

[90 51 77 60]
[1 3 2 0]


array([[33, 46, 51],
       [20, 14, 60],
       [77, 37, 76],
       [90, 57, 55]])

In [126]:
# iv. Sort based on elements value.
np.sort(mat, axis=None).reshape(mat.shape)

array([[14, 20, 33],
       [37, 46, 51],
       [55, 57, 60],
       [76, 77, 90]])

###`Q-2:` There is an array of marks of 5 students in 4 subjects. Further you are asked to perform below task.
    i. Add marks every student of an extra subject in the same array.
    ii. Add two new students marks in respective 5 subjects.(one subject added in above task)
    iii. Add extra column with sum of all subjects(5-subjects) marks
    iv. Sort the array(non-ascending order) on total marks column--one added in above task. Show top 2 rows.

Note: Change dimension of arrays during concatenation or appending if required.

Given Array-
```
marks = [[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]]

extra_subject = [41, 87, 72, 36, 92]
#Two extra students record-
rec1 = [77, 83, 98, 95, 89]
rec2 = [92, 71, 52, 61, 53]
```

In [140]:
marks = np.array(
    [[13, 10,  9, 33],
    [63, 46, 90, 42],
    [39, 76, 13, 29],
    [82,  9, 29, 78],
    [67, 61, 59, 36]]
)

extra_subject = np.array([41, 87, 72, 36, 92])
# i. Add marks every student of an extra subject in the same array.

# Step 1. reshape array to 5, 1
reshaped_extra_sub = extra_subject.reshape(5, 1)
# Step 2, vstack

array_after_adding_extra_marks = np.hstack((marks, reshaped_extra_sub))
array_after_adding_extra_marks


array([[13, 10,  9, 33, 41],
       [63, 46, 90, 42, 87],
       [39, 76, 13, 29, 72],
       [82,  9, 29, 78, 36],
       [67, 61, 59, 36, 92]])

In [ ]:
# ii. Add two new students marks in respective 5 subjects.(one subject added in above task)
rec1 = np.array([77, 83, 98, 95, 89])
rec2 = np.array([92, 71, 52, 61, 53])

res2 = np.vstack((array_after_adding_extra_marks, rec1, rec2))
res2

array([[13, 10,  9, 33, 41],
       [63, 46, 90, 42, 87],
       [39, 76, 13, 29, 72],
       [82,  9, 29, 78, 36],
       [67, 61, 59, 36, 92],
       [77, 83, 98, 95, 89],
       [92, 71, 52, 61, 53]])

In [159]:
# iii. Add extra column with sum of all subjects(5-subjects) marks
marks_sum_arr =  np.sum(res2, axis=1).reshape(res2.shape[0], 1)
res3 = np.hstack((res2, marks_sum_arr))
print(res3)

[[ 13  10   9  33  41 106]
 [ 63  46  90  42  87 328]
 [ 39  76  13  29  72 229]
 [ 82   9  29  78  36 234]
 [ 67  61  59  36  92 315]
 [ 77  83  98  95  89 442]
 [ 92  71  52  61  53 329]]


In [163]:
# iv. Sort the array(non-ascending order) on total marks column--one added in above task. Show top 2 rows.
res4 = res3[res3[:, -1].argsort()][::-1]
res4[:2]

array([[ 77,  83,  98,  95,  89, 442],
       [ 92,  71,  52,  61,  53, 329]])

###`Q-3:` Find unique arrays from a 2D array column wise and row wise.
```
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
```
Expected Result-
```
Row Wise
[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]

Col Wise
[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]
```

In [128]:
arr = np.array([
    [1,2,3,3,1,1],
    [0,9,1,2,8,8],
    [1,2,3,8,8,8],
    [1,2,3,3,1,1]
])
# 1. Row Wise unique elements
row_wise_unique = np.unique(arr, axis=0)
print("row wise", row_wise_unique)
# 2. Col wise unique elements
col_wise_unique = np.unique(arr, axis=1)
print("col wise \n", col_wise_unique)


row wise [[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]
col wise 
 [[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]


###`Q-4:` Flip given 2-D array along both axes at the same time.

In [129]:
arr2 = np.array([
    [1,2,3,3,1,1],
    [0,9,1,2,8,8]
])

np.flip(arr2, axis=0)

array([[0, 9, 1, 2, 8, 8],
       [1, 2, 3, 3, 1, 1]])

### `Q-5:` Get row numbers of NumPy array having element larger than X.
```
arr = [[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]]

X = 6
```

In [130]:
arr = np.array([
    [1,2,3,4,5],
    [10,-3,30,4,5],
    [3,2,5,-4,5],
    [9,7,3,6,5]
])
X = 6
# 1. Rows having greater than X
mask = (arr > 6).any(axis=1) # any True will work
rows_havin_greater_than_x = np.where(mask)[0]

rows_havin_greater_than_x

array([1, 3])

### `Q-6:` How to convert an array of arrays into a flat 1d array?


In [131]:
# These arrays are given.
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)
print("arr", arr1)
print("arr2", arr2)
print("arr3", arr3)
flatten_arr = np.concat([arr1, arr2, arr3])
flatten_arr

arr [0 1 2]
arr2 [3 4 5 6]
arr3 [7 8 9]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### `Q-7:` You are given a array. You have to find the minimum and maximum array element and remove that from the array.

```python
import numpy as np

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
```

In [132]:
np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
print(arr)
print(np.max(arr))
# remove only one occurance of max element
max_element_index = np.argmax(arr)
arr = np.delete(arr, max_element_index) 
print(np.max(arr))

# remove all ocurrances of max and min
max = np.max(arr)
min = np.min(arr)

final_ar = arr[(arr != max) & (arr != min)]
print(final_ar)
print("max", np.max(final_ar), "min", np.min(arr))

[[448 563 418 240 507 362 345 236 719 291 298 639 458 387 262 613 267 882
  181 425 790 635 889 818 872 967 277 470 336 920 917 295 557 830 506 385
  353 975 592 997 137 340 222 215 472 459 617 649 935 956 914 932 645 952
  921 490 527 972 278 307 840 958 246 449 251 957 103 627 920 824 356 825
  173 323 372 960 710 464 244 782 763 635 436 774 171 469 178 458 624 211
  771 270 308 231 952 514 699 702 433 900 373 318 998 265 503 320 230 324
  922 967 620 743 527 117 566 804 123 946 587 227 853 757 944 328 855 930
  325 729 426 514 296 879 575 936 705 209 191 743 510 513 628 559 658 528
  395 525 922 136 496 225 895 975 263 908 420 711 800 976 786 235 930 859
  618 226 695 460 218 483 490 803 621 453 193 607 677 637 728 724 534 748
  291 194 761 875 687 569 228 482 781 554 654 739 885 197 266 228 892 207
  883 588]]
998
997
[448 563 418 240 507 362 345 236 719 291 298 639 458 387 262 613 267 882
 181 425 790 635 889 818 872 967 277 470 336 920 917 295 557 830 506 385
 353 975 592 137 340

### `Q-8:` You are given an arrays. You have to limit this array's elements between 100 to 200. $arr ∈ [100, 700]$. So replace those values accordingly with the minimum and maximum value. Then sort the array and perform the cumulative sum of that array.

In [133]:
arr2 = np.random.randint(100, 1000, 10).reshape((1, 10))
# Step 1. Limit array b/w 100 to 700
limited_arr = arr2.clip(min=100, max=700)

# 2. Sort the limited array
sorted_arr = np.sort(limited_arr)

# 3. cummulative sum
cummlative_sum_arr = np.cumsum(sorted_arr)
cummlative_sum_arr


array([ 381,  775, 1202, 1680, 2163, 2668, 3241, 3930, 4630, 5330])

### `Q-9:` You are given a array ($arr ∈ [0, 1]$). First you have round off the elements upto 3 decimal places and compare that
- 0th percentile == minimum value of the array
- 100th percentile == maximum value of the array
- also find the difference betwen 51th percenile and 50th percentile values

In [134]:
arr = np.random.rand(10)
# 1. round upto 3 decimals
rounded_values_arr = np.round(arr, 3)
print("rounded values arr", rounded_values_arr)
# 2. 0th percentile
p0 = np.percentile(rounded_values_arr, 0)

# 3. 100th percentile
p100 = np.percentile(rounded_values_arr, 100)

print("0th == min:", p0 == rounded_values_arr.min())
print("100th == max:", p100 == rounded_values_arr.max())

# 4.50th and 51th percentile
p50 = np.percentile(rounded_values_arr, 50)
p51 = np.percentile(rounded_values_arr, 51)
diff = p51 - p50
print(p50, p51, diff)

print("p50:", p50)
print("p51:", p51)
print("difference:", diff)


rounded values arr [0.46  0.373 0.194 0.36  0.158 0.947 0.437 0.355 0.661 0.704]
0th == min: True
100th == max: True
0.405 0.41076 0.005759999999999987
p50: 0.405
p51: 0.41076
difference: 0.005759999999999987
