**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [2]:
import numpy as np

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.

In [8]:
v = np.zeros(11, dtype=int)
v[4] = 1
v

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0])

In [22]:
v1 = np.ones(11, dtype=int)
v1

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [ ]:
a = int(input())
b = int(input())

arr = np.random.rand()
print("array = ", arr)
avg = np.mean(arr)
print("average", avg)

array =  [[0.45821789 0.45645817 0.41993449 0.32000107 0.27920122]
 [0.65998533 0.46817488 0.94097571 0.13361875 0.67135817]
 [0.42096807 0.25060078 0.4290545  0.55810089 0.86027445]
 [0.47779907 0.91978003 0.48923078 0.37074191 0.46916929]
 [0.1328266  0.10741511 0.09326724 0.71627561 0.13081379]]
average 0.4493697516124109


###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [37]:
a = 5
b = 5

arr2d = np.ones((a, b), dtype=int)
arr2d[1:-1, 1:-1] = 0
arr2d

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [40]:
vector = np.random.uniform(0, 1, 10)
print(vector)

[0.46938186 0.5833221  0.75970314 0.4706254  0.84688845 0.58015753
 0.06743085 0.24243271 0.56860566 0.38130644]


In [41]:
# Create vector excluding 0 and 1
vector = np.linspace(0, 1, 12)[1:-1]

print(vector)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [ ]:
# no, identity matrix can only be created upon square matrix
identity_matrix = np.identity(3, dtype=int)
identity_matrix

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [50]:
five_to_five_mat = np.random.randint(0, 4, (5, 5))
five_to_five_mat


array([[0, 0, 2, 0, 2],
       [0, 3, 1, 1, 2],
       [2, 3, 1, 1, 0],
       [1, 0, 3, 1, 3],
       [0, 3, 0, 0, 2]])

In [70]:
# Create matrix
matrix = np.tile(np.arange(5), (5, 1))
print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [96]:
coordinates_arr = np.random.randint(1, 101, size=(10, 2))
# coordinates_arr = np.arange(1, 21).reshape(10, 2)
points = np.array([2, 3])
# distance_formula = sqrt((a2 - a1)**2 + (b2 - b1)**2)
print(coordinates_arr)
horizontally_diffrentiated_square = (coordinates_arr - points)**2
print(horizontally_diffrentiated_square)
sum_of_h_d_s = np.sum(horizontally_diffrentiated_square, axis=1)
distance_arr = np.sqrt(sum_of_h_d_s).astype(int)
distance_arr

[[ 52  52]
 [ 66  39]
 [ 82  66]
 [ 38  74]
 [ 19  54]
 [ 87  88]
 [  9  41]
 [100  39]
 [ 15  92]
 [ 23  54]]
[[2500 2401]
 [4096 1296]
 [6400 3969]
 [1296 5041]
 [ 289 2601]
 [7225 7225]
 [  49 1444]
 [9604 1296]
 [ 169 7921]
 [ 441 2601]]


array([ 70,  73, 101,  79,  53, 120,  38, 104,  89,  55])


###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [110]:
#Code here
x, y, z = (6, 7, 8)
arr = np.arange(1, (x*y*z + 1)).reshape((x, y, z))

arr[1, 5, 3]

np.int64(100)

### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [113]:
# arr = np.array([1, 2, 3, 4, -8, -10])
arr = np.array(input().split(), dtype=int)

reversed_arr = arr[::-1].astype(float)
reversed_arr

array([-19.,  -8.,   4.,   3.,   2.,   1.])

### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [184]:
arr = np.array([])

arr1 = np.array([1, 2])

arr.size
arr1.size

2

### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [ ]:
# arr = np.array([86.03331084, 37.7285648,  48.64908087, 87.16563062, 38.40852563, 37.20006318])
def calculate_softmax(arr):
    if not isinstance(arr, np.ndarray):
        raise TypeError("Input must be a numpy array.")
    if arr.ndim != 1:
        raise ValueError("Input must in 1D array.")
     # Subtracting max(arr) makes the largest element 0.
    # e^0 is 1, and everything else is less than 1. No more 'inf'!
    shift_arr = arr - np.max(arr)
    exponent_arr = np.exp(shift_arr) # e^arr[i]
    exponent_arr_sum = np.sum(exponent_arr) # sum(e^arr[i])
    softmax_arr = exponent_arr / exponent_arr_sum
    return softmax_arr

input_arr = np.array(input().split(), dtype=int)
softmax_op = calculate_softmax(input_arr)
softmax_op

array([0.09003057, 0.24472847, 0.66524096])

### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.


**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [129]:
def infinite_vertical_stacking(*args):
    if len(args) == 0:
        ValueError("Atleast one array is required.")

    for i, array in enumerate(args):
        if not isinstance(array, np.ndarray):
            raise TypeError(f"Argument at index {i} must be of numpy array.")
    
    vertical_stacked_arr = np.vstack(args)

    return vertical_stacked_arr

# Matrix a: Shape (2, 5)
a = np.array([[0, 1, 2, 3, 4],
              [5, 6, 7, 8, 9]])

# Matrix b: Shape (2, 5) 
# Elements must match the width of 'a'
b = np.array([[1, 1, 1, 1, 1],
              [1, 1, 1, 1, 1]])
c = np.array([
    [0.10117373, 0.1677244,  0.73764059, 0.83166097, 0.48985695],
    [0.44581567, 0.13502419, 0.55692335, 0.16479622, 0.61193593]
])
try:
    result = infinite_vertical_stacking(a, b, c)
    print(result)
except ValueError as e:
    print(f"Error Caught: {e}")


[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]


### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [193]:
def date_array(start, end):
    if not isinstance(start, str) or not isinstance(end, str):
        raise TypeError("Both start date and end dates must be strings.")
    
    try:
        start_dt = np.datetime64(start)
        end_dt = np.datetime64(end)
    except:
        raise ValueError("Invalid date format, use YYYY-M-D")

    if str(start_dt)[:4] != str(end_dt)[:4]:
        raise ValueError("Dates must be in the same year")
    
    if start_dt > end_dt:
        raise ValueError("Start date must be <= end date")
    
    end = np.datetime64(end) + np.timedelta64(1, 'D') #Include end date
    return np.arange(start, end, dtype='datetime64[D]')

res = date_array(start = '2020-11-25', end = '2020-11-30')
print(res)

['2020-11-25' '2020-11-26' '2020-11-27' '2020-11-28' '2020-11-29'
 '2020-11-30']


###`Q-14:` Subtract the mean of each row from a matrix.

In [139]:
matrix = np.arange(1, 17).reshape(4,  4)
mean = np.mean(matrix, axis=1, keepdims=True) # axis = 1 means, each row
print("mean", mean)
subtracted_mat = matrix - mean
subtracted_mat

mean [[ 2.5]
 [ 6.5]
 [10.5]
 [14.5]]


array([[-1.5, -0.5,  0.5,  1.5],
       [-1.5, -0.5,  0.5,  1.5],
       [-1.5, -0.5,  0.5,  1.5],
       [-1.5, -0.5,  0.5,  1.5]])

###`Q-15:` Swap column-1 of array with column-2 in the array.

In [144]:
matrix = np.arange(1, 17).reshape(4,  4)
print(matrix)
matrix[0::, [0, 1]] = matrix[0::, [1, 0]]
print("Matrix after swapping col-1 with col-2\n", matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Matrix after swapping col-1 with col-2
 [[ 2  1  3  4]
 [ 6  5  7  8]
 [10  9 11 12]
 [14 13 15 16]]


###`Q-16:` Replace odd elements in arrays with -1.

In [ ]:
matrix = np.arange(1, 17).reshape(4,  4)

matrix[matrix % 2 != 0] = -1 # in place

indices = np.where(matrix % 2!= 0, -1, matrix) # creates new matrix
indices


array([[-1,  2, -1,  4],
       [-1,  6, -1,  8],
       [-1, 10, -1, 12],
       [-1, 14, -1, 16]])

###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [155]:
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

res = np.maximum(a, b)
res

array([6, 3, 1, 7, 8])

###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [ ]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
# print("arr1", arr1)
alternate_cols = arr1[:,::2]
# print(alternate_cols)

def normalize_arr_x_min_max(arr):
    arr = np.asarray(arr, dtype=float)
    x_min = np.min(arr)
    x_max = np.max(arr)
    if x_max == x_min: # if both x_min and x_max are same then division by zero error will occur, so return all values as zero
        return np.zeros_like(arr)
    x_normalied = (arr - x_min) / (x_max - x_min)
    return x_normalied
print(normalize_arr_x_min_max(arr1))

[[9602 9745 6125 4169 3052]
 [3348 3664 3737   87  511]
 [7545 9722 7887 6034  118]
 [8210 4356 7271  462 8970]
 [2505  116 8825 3909 4730]
 [2129 4996 2619 4636 4951]
 [9144 1397 7476 8624 9059]
 [2748 9104 5757 4702 7867]]
xmin 87
x_max 9745
[[0.98519362 1.         0.6251812  0.42265479 0.30699938]
 [0.33764755 0.37036654 0.37792504 0.         0.04390143]
 [0.77220957 0.99761855 0.80762063 0.61575896 0.00320977]
 [0.8410644  0.44201698 0.7438393  0.03882791 0.91975564]
 [0.25036239 0.00300269 0.90474218 0.39573411 0.48074135]
 [0.21143094 0.50828329 0.26216608 0.47100849 0.50362394]
 [0.9377718  0.13563885 0.76506523 0.88393042 0.9289708 ]
 [0.27552288 0.93363015 0.58707807 0.4778422  0.8055498 ]]


In [ ]:
#Code here

###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [164]:
def find_nth_largest(arr, n):
    if n > len(arr):
        raise ValueError("n shold be <= size of arr")
    
    return np.partition(arr, -n)[-n]
arr = np.array([12,34,40,7,1,0])
print(find_nth_largest(arr, 1))

40


###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [172]:
a = np.array([1,2,3])
res = np.concatenate([
        np.repeat(a, 3),
        np.tile(a, 3)    
    ])
res

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

###Q21 With your high school reunion fast approaching, you decide to get in shape and lose some weight . You record your weight every day for five weeks starting on a Monday.
Given these daily weights, build an array with your average weight per weekend1.

In [69]:
import numpy as np

dailywts = 185 - np.arange(5*7)/5

print(dailywts)

saturday_weights = dailywts[5::7]
sunday_weights = dailywts[6::7]
weekend_weights = saturday_weights + sunday_weights
print("weekend weights", weekend_weights)
avg_weight_per_weekend = weekend_weights / 2
avg_weight_per_weekend


[185.  184.8 184.6 184.4 184.2 184.  183.8 183.6 183.4 183.2 183.  182.8
 182.6 182.4 182.2 182.  181.8 181.6 181.4 181.2 181.  180.8 180.6 180.4
 180.2 180.  179.8 179.6 179.4 179.2 179.  178.8 178.6 178.4 178.2]
weekend weights [367.8 365.  362.2 359.4 356.6]


array([183.9, 182.5, 181.1, 179.7, 178.3])